version: "3"

services:
  db:
    container_name: Tracker-MongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./datadb:/data/db

  api:
    build: ./tracker_api
    command: bash -c "npm run build && npm start"
    container_name: "Tracker-Backend"
    environment:
      TRACKER_ENV: ${TRACKER_ENV:-development}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: tracker:api
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./tracker_api:/tracker
      - api-packages:/tracker/node_modules
    depends_on:
      - db

  webui:
    build: ./tracker_webui
    command: bash -c "npm run build && serve dist"
    container_name: "Tracker-Frontend"
    environment:
      NODE_ENV: ${NODE_ENV:-local}
    image: tracker:webui
    ports:
      - "3000:8080"
    restart: always
    volumes:
      - ./tracker_webui:/tracker
      - webui-packages:/tracker/node_modules
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: "Tracker-Nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    depends_on:
      - webui

volumes:
  api-packages:
    name: api-packages
  webui-packages:
    name: webui-packages
